version: 2
updates:
  # Rust dependencies: Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    versioning-strategy: "lockfile-only"
    schedule:
      interval: "weekly"
    groups:
      lockfile:
        patterns:
          - "*"
